### PR TITLE
15 shared Loaded based on MUI

### LINKED ISSUE #15: Create reusable Loader using material ui component
try to make as configurable as possible, all properties should be exposed.

### PR DESCRIPTION
**Pull request by eLeontev**
#### Issue related
- Closes #15

#### What is being changed?
- add mui circular loader wrapper
- update eslint rules to consistent type instead of interface
- align types usages

####  Evidences
Added to the demonstration in LoginForm

https://user-images.githubusercontent.com/15786916/193459606-01ceaaca-792c-4cd5-b2f5-f4b3b9cc310c.mov

#### Observations

More details can be clarified during the review since criteria are pretty generic

### CODE REVIEW

**Comment by eLeontev** [comment]
build job has failureddue to a lot of eslint issues in the main branch. It's out of the MR scope to fix them. I suggest to create a separte issue to fix all inconsistencies.

ps please do not push commits to the main branch directly, since it looks like does not trigger your CI or configure CI to be able to handle it.

Please let me know if I can create a separate issue/or you will take care (I can fix the issues, so feel free to assign it to me)

**Comment by kishankr7979** [comment]
hey @eLeontev, please go ahead and create a issue to fill those linting/rules error.

**Comment by kishankr7979** [comment]
from today onwards, no will push directly to main branch

**Comment by eLeontev** [comment]
I've created an issue for it #21

this PR would be postponed until blocker is not resolved yet

**Comment by eLeontev** [comment]
> I've created an issue for it #21
> 
> this PR would be postponed until blocker is not resolved yet

the activity has completed. PR is unblocked and ready for review

**Comment by kishankr7979** [comment]
@eLeontev let's add a support to have linear progress as well, expose a props named as { type : 'LINEAR' | 'CIRCULAR' }

**Review by kishankr7979 — APPROVED** [review]

**Pull request merged**
